### ISSUE TITLE
Razzle-SSR example broken since 8.1.1

### ISSUE THREAD

**Issue by krazyjakee** [i18next/react-i18next#619] opened 2018-11-15 13:12 UTC
**Describe the bug**
Razzle-SSR example broken since 8.1.1.
https://github.com/i18next/react-i18next/tree/master/example/razzle-ssr

**Occurs in react-i18next version**
v8.1.1

**To Reproduce**
1. Clone example.
1. Add a second route
2. Click on NavLink from react-router-dom
3. URL changes, but the application doesn't rerender

**Expected behaviour**
Load the next page

**Comment by jamuhl** [comment] 2018-11-15 13:15
guess caused by https://github.com/i18next/react-i18next/commit/686c47898bef5a526dd85bb77dc8740f06894357#diff-e4eda667c493b066ae0e390d2ca16e52

hm...might consider rollback - or update the sample at some point. for now downgrading react-i18next to v6.x.x should make it work again.

**Comment by jamuhl** [comment] 2018-11-15 13:19
@a-barbieri could this be related to your PR?

**Comment by jamuhl** [comment] 2018-11-15 14:30
@kadishmal did you meant those external links? Guess yes, as there are no others. Sorry, @a-barbieri should have seen that myself...those are just links to external information no links to second page.

**Comment by krazyjakee** [comment] 2018-11-15 14:32
Damn, I see I missed that in the issue. I will update it.

That example needs a secondary route. Essentially the router is broken there when adding a second route.

**Comment by jamuhl** [comment] 2019-01-30 07:52
please start adding changes related to the v9 version to the v9.x.x branch (master will be now for the upcoming v10 hooks)

--> https://github.com/i18next/react-i18next/tree/v9.x.x

**Comment by jamuhl** [comment] 2019-02-07 16:57
closing for now...won't invest time in the v9 samples....hopefully we get a v10 sample up again at some point

**Closed by jamuhl** 2019-02-07 16:57 UTC
Labels: help wanted, v9
