### ISSUE TITLE
Onloaded event not firing

### ISSUE THREAD

**Issue by collinpage** [i18next/react-i18next#633] opened 2018-12-03 17:58 UTC
I'm trying to use the Onloaded event but it never seems to fire. I tried with the onLanguageChanged event and it worked fine.

Here is the code I'm using:
```
import i18n from 'i18next';

import { fr_ca } from '../locales/fr_ca.js';
import { en_ca } from '../locales/en_ca.js';

let lng = typeof window !== 'undefined' ? (window.location.pathname).split("/")[1] : "en";

i18n.init({
  lng: lng,
  whitelist: ['en', 'fr'],
  fallbackLng: 'en',
  resources: {
    en: en_ca,
    fr: fr_ca
  },
  debug: false,

  interpolation: {
    escapeValue: false // not needed for react!!
  }
});

i18n.on('loaded', function(loaded) {
  console.log('hello world');
});

export default i18n;
```

Any clues why is that so?

**Comment by jamuhl** [comment] 2018-12-03 19:51
on loaded event triggers only when the backend loads a translation file - your code directly imports the translations as options.resources -> therefore, no onLoaded event!!! Guess onInitialized is what you need.

**Comment by jamuhl** [comment] 2018-12-05 19:43
closing this - by design

**Closed by jamuhl** 2018-12-05 19:43 UTC
