### ISSUE TITLE
NextJs Sample: The page refresh after it fully loaded

### ISSUE THREAD

**Issue by shakesBeardZ** [i18next/react-i18next#597] opened 2018-10-31 17:25 UTC
Hi guys, in the recent days I've noticed  that my app(based on nextJS sample) get refreshed everytime when it fully loaded, and I also checked that in the sample and it's the same thing so anyone has experienced that? and how to get rid of it 

<a href="https://gyazo.com/bcda10a86cc6d391cbcc8c8015df2874"><img src="https://i.gyazo.com/bcda10a86cc6d391cbcc8c8015df2874.gif" alt="Image from Gyazo" width="800"/></a>

**Comment by isaachinman** [comment] 2018-11-02 00:12
@shakesBeardZ Please let us know if you want to proceed with trying to debug this.

**Comment by shakesBeardZ** [comment] 2018-11-02 12:34
@isaachinman the problem exist in nextJs sample and I think it's because of the router replace 
`        Router.replace(correctedPath, correctedPath, { shallow: true });
`
even though shollow is true but still redresh the page after the url in the adress bar changes , I mean it's loads the specific language and render it them do th refresh 

<a href="https://gyazo.com/2ea58d46b9877071c83e043f4cec29a0"><img src="https://i.gyazo.com/2ea58d46b9877071c83e043f4cec29a0.gif" alt="Image from Gyazo" width="800"/></a>

and when you put in production I think it's desirable from UX prespective.
so if have any suggestion on how to get rid of it.

**Comment by isaachinman** [comment] 2018-11-02 23:14
I still don't clearly understand the problem. Perhaps instead of GIFs, can you write how I can reproduce the problem, step by step?

**Comment by Nelrohd** [comment] 2018-11-03 04:48
I have the same problem and I use in my app:
```
module.exports = {
    translation: {
      // default / fallback language
      defaultLanguage: 'fr',
      localesPath: './static/locales/',
  
      // needed for serverside preload
      allLanguages: ['en', 'fr'],
  
      // optional settings needed for subpath (/de/page1) handling
      enableSubpaths: false,
      subpathsOnNonDefaultLanguageOnly: false, // only redirect to /lng/ if not default language
    },
  };
```
I will try to reproduce the problem with the demo

**Comment by Nelrohd** [comment] 2018-11-03 05:05
In fact, just download the current nextjs demo, do `npm i && npm run dev` and you can see the problem that @shakesBeardZ describes.

Note: if I use the link provided by the readme in examples/nextjs, I get the demo for the 7.x.x of react-i18next.

**Comment by Nelrohd** [comment] 2018-11-03 05:12
More info for reproducing the problem:
1. Disable subpath in `config.js` -> `enableSubpaths: false,`
2. Fix bug when ctx.req is undefined in `pages/_app`
```
static async getInitialProps({ ctx }) {
    return {
      initialLanguage: (ctx.req && ctx.req.language) ?
        ctx.req.language : translation.defaultLanguage
    };
  };
```
3. Replace all the `<Link>` with `<a>`, so:
```
<Link href="/">
      <a>{t('link.gotoPage1')}</a>
</Link>
```
Becomes
```
<a href="/">{t('link.gotoPage1')}</a>
```
4. `npm run dev` and click any links, you will notice a quick flash

**Comment by Nelrohd** [comment] 2018-11-03 05:15
Note 2: I completely removed everything in `lib/languagePathCorrection.js` based on @shakesBeardZ assumption but the bug is still there
```
import config from '../config';
import i18n from '../i18n';

const { defaultLanguage, allLanguages, subpathsOnNonDefaultLanguageOnly } = config.translation;

export default (currentRoute, currentLanguage = i18n.languages[0]) => {
  return currentRoute;
};
```
Anyway, I don't think it changes much since `enableSubpaths` is `false`.

**Comment by antandev** [comment] 2018-11-03 08:42
> Hi guys, in the recent days I've noticed that my app(based on nextJS sample) get refreshed everytime when it fully loaded, and I also checked that in the sample and it's the same thing so anyone has experienced that? and how to get rid of it
> 
> [<img alt="Image from Gyazo" width="800" src="https://camo.githubusercontent.com/f6f09b2909175ba4311cc2d35c0ef057a62e1ca3/68747470733a2f2f692e6779617a6f2e636f6d2f62636461313061383663633664333931636263633863383031356466323837342e676966">](https://gyazo.com/bcda10a86cc6d391cbcc8c8015df2874)

i think know what you mean, because i have the same problem, and the problem in not on nextjs but server.js.

notice when there's no cookies in your browser, it doesn't have path '/en/' however when you change language it store /en/ to cookie, so when you try access the url without '/en/' it will redirect to '/en/' because in server.js the code use middleware to detect the cookie and redirect them

`
...
if (enableSubpaths) {
  server.get('*', (req, res, cb) => {
    const { pathname, search } = parseURL(req.url);
    const searchString = search || '';
    allLanguages.forEach(lng => {
      if (pathname.startsWith(`/${lng}`) && !pathname.startsWith(`/${lng}/`)) {
        res.redirect(301, pathname.replace(`/${lng}`, `/${lng}/`) + searchString);
      }
    });
    cb();
  });
}
...
`

that's why the browser will reload the page when you enter without '/en/', and i am trying to change the redirect with something similar but to replace the path not redirect the page

**Comment by jamuhl** [comment] 2018-11-03 11:40
might be related to: https://github.com/i18next/react-i18next/issues/600#issuecomment-435369595 point 1)

**Comment by isaachinman** [comment] 2018-11-03 15:48
This is a genuine issue. Unsurprisingly, if I revert to `73e33b8`, the issue goes away. We need to look at commit history since then and debug. I do not have time this weekend, but can take a deeper looker into this early next week. Apologies to everyone in the meantime - it's a work in progress.

**Comment by isaachinman** [comment] 2018-11-03 15:51
If anyone has time to do a `git bisect` on this and find the bad commit before Monday, that would be incredibly helpful.

**Comment by revskill10** [comment] 2018-11-03 19:12
You can look at my commit [here](https://github.com/i18next/react-i18next/pull/555) , and the issue might have gone.
I have no issue till now with apollo and react-i18next.

**Comment by isaachinman** [comment] 2018-11-03 21:05
I'm not sure why @revskill10's commits were merged in the first place. They contained several critical bugs... the app didn't even run. @jamuhl Any idea what happened there? I haven't been aware of these recent changes to the NextJs example source.

I do not think it's a good idea to be persisting app state in localStorage or cookies in this example. Same rationale as with RN - persistence belongs in user land.

**Comment by isaachinman** [comment] 2018-11-03 21:28
@jamuhl Agree about keeping that within the language detection plugin.

**Comment by isaachinman** [comment] 2018-11-03 21:39
So, let's get back to the actual topic here. This refresh issue seems to be introduced as a regression with 3c20461, which was a bug fix for another issue.

The problem is that the `initialLanguage` logic was rerunning on the client, where the `req` is never available, and was being reset to the `defaultLanguage` every time. Pretty straightforward bug. The real issue here is a misunderstanding - the `initialLanguage` logic belongs in a `_document.js`, _not_ an `_app.js`, because we only want to run that server side. We can then pass the value into `_app.js` via `pageProps`.

I've already created #608 to fix this bug.

That being said - @jamuhl if you are fine with it, let's leave the NextJs example source completely untouched until I can take a deep look at it next week when I am back in the office. I wasn't aware that this example was going to get so much use, and I think a fresh rewrite might be the best approach.

**Comment by jamuhl** [comment] 2018-11-04 09:06
@isaachinman fully agree...seems next.js is right now top hot topic nr. 1 here - so i stand 200% behind your decisions

**Comment by Nelrohd** [comment] 2018-11-04 11:00
@isaachinman In fact it does not work since you can't pass props to App component that way
https://github.com/i18next/react-i18next/pull/608/files#diff-3d33fc272b5b5d8cd4d515bd7939050dR19
So your fix works because initialLanguage is undefined in App

We should use the new feature `enhancedApp` used to pass props from `_document` to `_app` https://github.com/zeit/next.js/pull/4762/files#diff-ac08f8853956c0ef691e75a44d94cb03R5

**Comment by Nelrohd** [comment] 2018-11-04 11:15
This is my `_document`, however it does not fix the flash
```

import React from 'react';
import Document, { Head, Main, NextScript } from 'next/document';
import { translation } from '../i18n-config';
import flush from 'styled-jsx/server';

export default class extends Document {
  static async getInitialProps(ctx) {
    const { req } = ctx;
    let initialLanguage = req.language ? req.language : translation.defaultLanguage;

    const enhanceApp = Component => (props) => <Component {...props} initialLanguage={initialLanguage} />
    const page = ctx.renderPage({ enhanceApp });
    const styles = flush();

    return {
      ...page,
      styles,
      initialLanguage,
    };
  }

  render() {
    const { initialLanguage } = this.props;

    return (
      <html lang={initialLanguage}>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

**Comment by Nelrohd** [comment] 2018-11-04 11:47
If I remove `wait={process.browser}` from `NamespacesConsumer`, no more flash but of course we can see the text changing to the initial language translations.

**Comment by isaachinman** [comment] 2018-11-04 17:47
Hi @Nelrohd. What makes you think you can't pass props into the NextJs `Main`? In my testing, `intialLanguage` in `pageProps` was definitely defined, but it could have been coming from the language detector plugin.

Perhaps you can join the discussion in #609? We'd rather do a solid rewrite rather than keep patching the existing solution.

**Closed as completed** 2018-11-09 20:25 UTC
Labels: bug
