### ISSUE TITLE
How to use Hook within function

### ISSUE THREAD

**Issue by Jean-PhilippeD** [i18next/react-i18next#836] opened 2019-04-26 13:33 UTC
Hello,

I'm trying to use react-i18next and I got this error : 

> Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.

i'm just tryign to wrap a toast notification like this : 

```
import { toast } from 'react-semantic-toasts';
import { useTranslation } from 'react-i18next'

export function NotifySuccess(title, message='') {
    const { t, i18n } = useTranslation();

    toast({
        type: 'success',
        icon: 'thumbs up outline',
        title: title,
        description: t(message),
        animation: 'bounce',
        time: 5000,
    });
}
```

As I'm pretty new to react.js, I understand I might not being able to load the hook within this function but I don't know how to handle this.

**Comment by jamuhl** [comment] 2019-04-26 14:02
Do you use `useTranslation` somewhere else - in class?!?

**Comment by Jean-PhilippeD** [comment] 2019-04-26 14:18
nope, this function is called from others class

**Comment by jamuhl** [comment] 2019-04-26 15:37
react, react-dom same version and > 16.8.x

makes no sense...

**Comment by redbugz** [comment] 2019-04-26 17:56
We get that message when we get multiple copies of React in our bundle, usually because a dependency bundled react with their code.

**Comment by Jean-PhilippeD** [comment] 2019-04-30 13:28
react and react-dom are both 16.8.6

**Comment by jamuhl** [comment] 2019-05-16 13:33
can't reproduce...closing for now...

**Closed by jamuhl** 2019-05-16 13:33 UTC
