### ISSUE TITLE
React 18 - Trans component interpolation issue

### ISSUE THREAD

**Issue by enoh-barbu** [i18next/react-i18next#1490] opened 2022-04-27 14:38 UTC
I've just upgraded to react v18 but I get an error while doing interpolation using Trans component

```
<Trans i18nKey="pageNrOfAll" pageNr={pageNr} pagesCount={pagesCount}>
    Page
    <strong className="spacing">{{ pageNr }}</strong>
    of
    <strong className="spacing">{{ pagesCount }}</strong>
 </Trans>
```
![image](https://user-images.githubusercontent.com/24221572/165543530-02cc0e7e-cdc9-446e-b001-f9814c51302e.png)

```
Type '{ pageNr: number; }' is not assignable to type 'ReactNode'.
  Object literal may only specify known properties, and 'pageNr' does not exist in type 'ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal'.ts(2322)
index.d.ts(1375, 9): The expected type comes from property 'children' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'
```
If I keep only one pair of brackets `{ pageNr }` I get the following error

`react-i18next:: Trans: the passed in value is invalid - seems you passed in a variable like {number} - please pass in variables for interpolation as full objects like {{number}}.`

[https://codesandbox.io/s/brave-bohr-obwf63](https://codesandbox.io/s/brave-bohr-obwf63)

I've just posted the same question on [stackoverflow](https://stackoverflow.com/questions/72030446/react-18-react-i18next-trans-component-interpolation-issue)

**Comment by adrai** [comment] 2022-04-27 15:47
probably duplicate of #1483

**Closed** 2022-05-05 05:00 UTC
Labels: typescript

**Comment by adrai** [comment] 2022-05-05 05:04
v11.16.8 offers allowObjectInHTMLChildren option
