### ISSUE TITLE
Upgrade from 7.12.0 to 8.0.7 fails with "Cannot read property 'bind' of undefined"

### ISSUE THREAD

**Issue by ocean90** [i18next/react-i18next#539] opened 2018-10-09 11:09 UTC
Stack of the error:

```
Uncaught TypeError: Cannot read property 'bind' of undefined
    at I18nextProvider.render (I18nextProvider.js:46) // https://github.com/i18next/react-i18next/blob/v8.0.7/src/I18nextProvider.js#L30
    at finishClassComponent (react-dom.development.js:13538)
    at updateClassComponent (react-dom.development.js:13501)
    at beginWork (react-dom.development.js:14090)
    at performUnitOfWork (react-dom.development.js:16416)
    at workLoop (react-dom.development.js:16454)
    at HTMLUnknownElement.callCallback (react-dom.development.js:145)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:195)
    at invokeGuardedCallback (react-dom.development.js:248)
    at replayUnitOfWork (react-dom.development.js:15745)
    at renderRoot (react-dom.development.js:16548)
    at performWorkOnRoot (react-dom.development.js:17387)
    at performWork (react-dom.development.js:17295)
    at performSyncWork (react-dom.development.js:17267)
    at requestWork (react-dom.development.js:17155)
    at scheduleWork (react-dom.development.js:16949)
    at scheduleRootUpdate (react-dom.development.js:17637)
    at updateContainerAtExpirationTime (react-dom.development.js:17664)
    at updateContainer (react-dom.development.js:17691)
    at ReactRoot.render (react-dom.development.js:17957)
    at eval (react-dom.development.js:18097)
    at unbatchedUpdates (react-dom.development.js:17518)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:18093)
    at Object.hydrate (react-dom.development.js:18149)
    at renderReactElement (index.js:340)
    at _callee5$ (index.js:404)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:288)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/_next/static/runtime/main.js:940:21)
    at asyncGeneratorStep (asyncToGenerator.js:5)
    at _next (asyncToGenerator.js:27)
    at asyncToGenerator.js:34
    at new Promise (<anonymous>)
    at new F (_export.js:36)
    at asyncToGenerator.js:23
    at _doRender (index.js:464)
    at doRender (index.js:349)
    at _callee2$ (index.js:239)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:288)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/_next/static/runtime/main.js:940:21)
    at asyncGeneratorStep (asyncToGenerator.js:5)
    at _next (asyncToGenerator.js:27)
    at asyncToGenerator.js:34
    at new Promise (<anonymous>)
    at new F (_export.js:36)
    at asyncToGenerator.js:23
    at _render (index.js:260)
    at render (index.js:211)
    at _callee$ (index.js:190)
```

This is a Next.js application and the configs are mostly copied from the [example](https://github.com/zeit/next.js/tree/7.0.1/examples/with-react-i18next). For additional context the code of some of the relevant files:

####  `withI18next.js`:

<details>

```js
import { translate, loadNamespaces } from 'react-i18next'
import i18n from 'i18n'
import { NAMESPACES } from 'constants/i18n'

const withI18next = ( namespaces = NAMESPACES ) => ComposedComponent => {
	const Extended = translate( namespaces, { i18n, wait: true } )(
		ComposedComponent
	)

	Extended.getInitialProps = async ( ctx ) => {
		const composedInitialProps = ComposedComponent.getInitialProps
			? await ComposedComponent.getInitialProps( ctx )
			: {}

		const i18nInitialProps = ctx.req
			? i18n.getInitialProps( ctx.req, namespaces )
			: await loadNamespaces( {
				components: [ { props: { namespaces } } ],
				i18n: i18n,
			} )

		return {
			...composedInitialProps,
			...i18nInitialProps,
		}
	}

	Extended.displayName = `withI18next(${ComposedComponent.displayName})`

	return Extended
}

export default withI18next
```

</details>

#### `_app.js`:

<details>

```js
import React from 'react'
import { Provider as ReduxProvider } from 'react-redux'
import App, { Container } from 'next/app'
import Router from 'next/router'
import withRedux from 'next-redux-wrapper'
import initStore from 'store'
import { I18nextProvider } from 'react-i18next'
const i18n = require( 'i18n' )

class CustomApp extends App {
	static async getInitialProps( { Component, ctx } ) {
		return {
			pageProps: ( Component.getInitialProps ? await Component.getInitialProps( ctx ) : {} ),
		}
	}

	render() {
		const { Component, pageProps, store } = this.props

		return (
			<Container>
				<ReduxProvider store={ store }>
					<I18nextProvider i18n={ ( pageProps && pageProps.i18n ) || i18n }>
						<Component { ...pageProps } />
					</I18nextProvider>
				</ReduxProvider>
			</Container>
		)
	}
}

export default withRedux( initStore )( CustomApp )
```

</details>

#### `i18n.js`:

<details>

```js
import i18next from 'i18next'
import XHR from 'i18next-xhr-backend'
import LngDetector from 'i18next-browser-languagedetector'
import {
	NAMESPACES,
	DEFAULT_LANGUAGE,
} from 'constants/i18n'
import { format as dateFormat } from 'date-fns'

const options = {
	fallbackLng: DEFAULT_LANGUAGE.toLowerCase(),
	load: 'languageOnly',

	ns: NAMESPACES,
	defaultNS: 'common',

	debug: false,

	interpolation: {
		escapeValue: false,
		formatSeparator: ',',
		format: ( value, format ) => {
			if ( value instanceof Date ) {
				return dateFormat( value, format )
			}

			return value
		},
	},
}

// For browser use xhr backend to load translations and browser lng detector
if ( process.browser ) {
	options.detection = {
		order: [ 'querystring', 'cookie', 'navigator' ],
		lookupCookie: 'language',
		lookupQuerystring: 'language',
		caches: [ 'cookie' ],
	}

	i18next
		.use( XHR )
		.use( LngDetector )
}

// Initialize if not already initialized.
if ( ! i18next.isInitialized ) {
	i18next.init( options )
}

// A simple helper to getInitialProps passed on loaded i18n data.
i18next.getInitialProps = ( req, namespaces = i18next.options.defaultNS ) => {
	const namespacesArray = Array.isArray( namespaces ) ? namespaces : [ namespaces ]

	req.i18n.toJSON = () => null

	const initialI18nStore = {}
	req.i18n.languages.forEach( ( l ) => {
		initialI18nStore[ l ] = {}
		namespacesArray.forEach( ( ns ) => {
			initialI18nStore[ l ][ ns ] = ( req.i18n.services.resourceStore.data[ l ] || {} )[ ns ] || {}
		} )
	} )

	return {
		i18n: req.i18n,
		initialI18nStore,
		initialLanguage: req.i18n.language,
	}
}

export default i18next
```
</details>

#### Snippet of `server.js`:

<details>

```js
// ....
import i18nMiddleware, { LanguageDetector } from 'i18next-express-middleware'
import { default as i18nBackend } from 'i18next-node-fs-backend'
import i18n from 'i18n'
import {
	NAMESPACES,
} from 'constants/i18n'

const { publicRuntimeConfig: { AVAILABLE_LANGUAGES, DEFAULT_LANGUAGE } } = getConfig()

// Init i18next with server-side settings.
i18n
	.use( i18nBackend )
	.use( LanguageDetector )
	.init( {
		fallbackLng: DEFAULT_LANGUAGE.toLowerCase(),
		preload: AVAILABLE_LANGUAGES.map( language => language.toLowerCase() ),
		whitelist: AVAILABLE_LANGUAGES.map( language => language.toLowerCase() ),
		ns: NAMESPACES,
		fallbackNS: 'common',
		backend: {
			loadPath: path.join( __dirname, '/locales/{{lng}}/{{ns}}.json' ),
		},
		detection: {
			order: [ 'querystring', 'cookie', 'header' ],
			lookupCookie: 'language',
			lookupQuerystring: 'language',
			caches: [ 'cookie' ],
		},
	}, () => { // ....
```

</details>

<br>

Beside the deprecation of the `translate()` HOC (changing it to `withNamespaces()` didn't solve this issue) I couldn't find something in the changelog which may be causing this issue. What am I missing?

**Comment by jamuhl** [comment] 2018-10-09 11:15
please upgrade next.js like: https://github.com/i18next/react-i18next/tree/master/example/nextjs fixes most problems with v7 with nextjs

**Comment by jamuhl** [comment] 2018-10-09 11:21
At some point you set the provider passing no real i18n instance to it -> guess happens here

```js
					<I18nextProvider i18n={ ( pageProps && pageProps.i18n ) || i18n }>
						<Component { ...pageProps } />
					</I18nextProvider>
```

might be that pageProps.i18n gets passed as empty object....not sure why but remembering i saw that once while migrating over...just check you get a i18n instance down on server and clientside.

But i highly recommend updating your code like in the new sample.

**Comment by jamuhl** [comment] 2018-10-09 11:31
ah...yes...it's an object - but i remember right ... that sometimes only is a JSON serialized "thing" having serializable members but misses the functions

try: `<I18nextProvider i18n={ pageProps && pageProps.i18n && pageProps.i18n.t ? pageProps.i18n :  i18n }>`

not remember what i did in our sample but had this temporary too - until fixed something deeper in the code of the sample - sorry for not remember what was the root cause anymore.

**Comment by jamuhl** [comment] 2018-10-16 11:35
still an issue?

**Comment by jamuhl** [comment] 2018-10-20 17:49
closing this now...feel free to reopen if still an issue

**Closed** 2018-10-20 17:50 UTC
Labels: can not reproduce
