### ISSUE TITLE
useSuspense warning printed to console despite debug flag set to "false"

### ISSUE THREAD

**Issue by alex-vukov** [i18next/react-i18next#1351] opened 2021-08-03 11:21 UTC
## 🐛 Bug Report

Using react-i18next with useSuspense intentionally set to "false" we get the following warning in console in production:
`react-i18next:: It seems you are still using the old wait option, you may migrate to the new useSuspense behaviour.`

We have "debug" set to disabled so this shouldn't be displayed. Also the warning is misleading because Suspense is still an experimental React feature (unless used with lazy()).

## To Reproduce

Run any react-i18next example with useSuspense set to false.

## Expected behavior

The warning should not be there.

## Your Environment

- node v14
- i18next version 19.8.5
- react-i18next version 11.8.5

**Comment by adrai** [comment] 2021-08-03 11:22
based on the log message, you're using the wait option

**Comment by adrai** [comment] 2021-08-03 11:30
Not able to reproduce it, when not using the old wait option....
Will close this issue, it can be reopened if you provide a reproducible example without configuring the wait option at all.

**Closed by adrai** 2021-08-03 11:30 UTC
