### ISSUE TITLE
Trans component returns an object instead of a component

### ISSUE THREAD

**Issue by rajivshah3** [i18next/react-i18next#374] opened 2018-01-05 05:51 UTC
I have the Trans component set up like this, just like the example, but it gives me an error for some reason

```
                       <Trans i18nKey="namespace:infoText">
                            <Text style={styles.infoText}>
                                <Text style={styles.infoTextLight}>One</Text>
                                <Text style={styles.infoTextRegular}>Two</Text>
                                <Text style={styles.infoTextLight}>Three</Text>
                                <Text style={styles.infoTextRegular}>Four</Text>
                                <Text style={styles.infoTextLight}>Five</Text>
                            </Text>
                        </Trans>
```

![image](https://user-images.githubusercontent.com/19519564/34597087-9849be04-f1b2-11e7-9a29-d6d6c4bb1f5a.png)

**Comment by jamuhl** [comment] 2018-01-05 07:57
Was this error given just when adding the Trans component or after adding some translation for it?

**Comment by rajivshah3** [comment] 2018-01-05 07:58
After adding the Trans component

**Comment by jamuhl** [comment] 2018-01-05 08:03
Will need to check...on the expo sample

**Comment by jamuhl** [comment] 2018-01-05 08:27
Hopefully will find time later today

**Comment by jamuhl** [comment] 2018-01-05 19:41
Just updated the sample: https://github.com/i18next/react-i18next/commit/d9740b4ed3c0b6ca29c9ac90304fa93f46ccb683

has no a Trans usage inside: https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/pages/Page2.js#L19

with translations: https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/i18n.js#L38

Could not reproduce your issue...do you have another than latest version of react-i18next installed?

**Comment by jamuhl** [comment] 2018-01-11 13:08
any update on this?

**Comment by rajivshah3** [comment] 2018-01-11 17:08
Hi,
Thanks so much for your help. I followed the sample but was still getting the same error. Right now I’m upgrading our version of react-native to see if that will sort out the issue (we’re pretty behind anyway). I’ll see if that fixes it

**Comment by jamuhl** [comment] 2018-01-11 20:30
thanks for the update

**Comment by jamuhl** [comment] 2018-01-11 20:32
if your on an old version you might need to set: `parent` https://react.i18next.com/components/trans-component.html#props

can be set globally on i18next.init -> defaultTransParent https://react.i18next.com/components/trans-component.html#additional-options-on-i18nextinit

as react < 16 does not allow to return multiple elements and need some wrapper -> set it to react-native's View should solve it i believe.

**Comment by mariegodon** [comment] 2018-01-20 01:28
I have been able to reproduce the issue on this [sandbox](https://codesandbox.io/s/xlnx7xloqw) using react 15.6 and redux 3.7.1.

**Comment by jamuhl** [comment] 2018-01-22 12:28
closing for now...feel free to reopen if not solved

**Closed by jamuhl** 2018-01-22 12:28 UTC
Labels: can not reproduce

**Comment by rajivshah3** [comment] 2018-01-23 17:27
@jamuhl we updated and it works now! Thanks for your help
