### ISSUE TITLE
Allow use of object notation in Trans components prop

### ISSUE THREAD

**Issue by rubystephenpoole** [i18next/react-i18next#976] opened 2019-10-23 20:18 UTC
In cases where a translation's components change order in different languages, the index-based notation no longer works.

It would be nice to able to specify an object key instead, which would make ordering a non-issue.

For example:

**The current case**
en/common.json
`
{
    "test": "This is a test translation where <1>ordering changes between languages</1>."
}
`
fr/common.json
`
{
     "test": "<0>Le this is a test translation</0> where ordering changes between languages."
}
`
`
<Trans
            i18nKey="test"
            components={[<b></b>]}
/>
`

**Proposed solution**
en/common.json
`
{
    "test": "This is a test translation where <bolded>ordering changes between languages</bolded>."
}
`
fr/common.json
`
{
     "test": "<bolded>Le this is a test translation</bolded> where ordering changes between languages."
}
`
`
<Trans
            i18nKey="test"
            components={{ bolded: <b></b> }}
/>
`

**Comment by jamuhl** [comment] 2019-10-23 20:19
closing as duplicate of https://github.com/i18next/react-i18next/issues/833

**Closed by jamuhl** 2019-10-23 20:19 UTC
