### ISSUE TITLE
i18Next rendering twice and the page flashed

### ISSUE THREAD

**Issue by retep0214** [i18next/react-i18next#626] opened 2018-11-27 14:30 UTC
I used Next.js + react-i18next to build a website.

I find that the website will be reloaded when the first loading. It is not actually reloaded via browser, is like the element hides suddenly and shows suddenly )

I try to disable the server side CSS (styled-component of _document.js) and the page will show like the CSS loaded after rendering. Then I try to disable the i18Next (Delete the i18NextProvider and do not use i18n in the page), The page does not have the reload problem. So I think that the problem in the i18Next trigger the reloads between server-side render and client-side rendering.

All API will be called in server-side, so I think the server side-rendered code is perfect already. So I have some Ideas to solve this problem but I don't know how to do it.

1) Prevent the client side rendering when the First Load 
2) Only update the difference between Server-side and Client-Side, do not reload the whole container

Here is my files.

server.js

    // @flow weak
    
    const express = require('express')
    const path = require('path')
    const next = require('next')
    
    const dev = process.env.NODE_ENV !== 'production'
    const app = next({ dev, dir: './src' })
    const handle = app.getRequestHandler()
    
    const i18nextMiddleware = require('i18next-express-middleware')
    const Backend = require('i18next-node-fs-backend')
    const i18n = require('./i18n')
    const i18nCallBack = () => {
      app.prepare().then(() => {
        const server = express()
    
        server.use(i18nextMiddleware.handle(i18n))
    
        server.use('/locales', express.static(path.join(__dirname, '/locales')))
    
        server.get('*', (req, res) => {
          handle(req, res)
        })
    
        return server.listen(3000, err => {
          if (err) throw err
          console.log('> Ready on http://localhost:3000')
        })
      })
    }
    i18n
      .use(Backend)
      .use(i18nextMiddleware.LanguageDetector)
      .init(
        {
          fallbackLng: 'zh',
          preload: ['zh', 'en'],
          ns: ['common', 'menu', 'card', 'welcome'],
          backend: {
            allowMultiLoading: false,
            loadPath: path.join(__dirname, '/locales/{{lng}}/{{ns}}.json'),
            addPath: path.join(__dirname, '/locales/{{lng}}/{{ns}}.missing.json')
          }
        },
        i18nCallBack
      )
    
    module.exports = i18nCallBack

i18n.js

    // @flow strict
    
    const i18n = require('i18next')
    const XHR = require('i18next-xhr-backend')
    const LanguageDetector = require('i18next-browser-languagedetector')
    
    const options = {
      fallbackLng: 'zh',
      lng: 'zh',
      load: 'languageOnly',
      ns: ['common'],
      defaultNS: 'common',
      debug: false,
      saveMissing: true,
      interpolation: {
        escapeValue: false,
        formatSeparator: ',',
        format: (value, format) => {
          if (format === 'uppercase') return value.toUpperCase()
          return value
        }
      },
      preload: ['en', 'zh']
    }
    
    // $FlowFixMe
    if (process.browser) {
      i18n.use(XHR).use(LanguageDetector)
    }
    
    if (!i18n.isInitialized) i18n.init(options)
    
    /* eslint-disable fp/no-mutation */
    i18n.getInitialProps = (req, namespaces) => {
      let nss = namespaces
      if (!namespaces) nss = i18n.options.defaultNS
      if (typeof nss === 'string') nss = [nss]
    
      req.i18n.toJSON = () => null
    
      const initialI18nStore = {}
      req.i18n.languages.forEach(l => {
        initialI18nStore[l] = {}
        nss.forEach(ns => {
          initialI18nStore[l][ns] =
            (req.i18n.services.resourceStore.data[l] || {})[ns] || {}
        })
      })
    
      return {
        i18n: req.i18n,
        initialI18nStore,
        initialLanguage: req.i18n.language
      }
    }
    
    /* eslint-enable fp/no-mutation */
    module.exports = i18n

**Comment by jamuhl** [comment] 2018-11-27 14:36
can you set debug true on init options and check if there were translations loaded which causes that flickering....for me it looks like not all needed translations are passed down to the client in initialI18nStore

**Comment by jamuhl** [comment] 2018-11-27 14:36
or at least check on client if there is a unwanted xhr request for translations

**Comment by MathiasKandelborg** [comment] 2018-11-28 13:42
I'm also experiencing this. There's XHR request in the client and everything seems to be configured correctly when I inspect the debug output: 

From this file:
```
/* eslint-disable global-require */

/* User Settings - feel free to change */
const PORT = process.env.PORT || 3333;

/* I18M */
const DEFAULT_LANGUAGE = 'da';
const OTHER_LANGUAGES = ['en'];
const DEFAULT_NAMESPACE = 'common';
const LOCALE_PATH = 'static/locales';
const LOCALE_STRUCTURE = '{{lng}}/{{ns}}';
const LOCALE_SUBPATHS = true;

/* Core Settings - only change if you understand what you're changing */
const config = {
  port: PORT,
  translation: {
    debug: true,
    allLanguages: OTHER_LANGUAGES.concat([DEFAULT_LANGUAGE]),
    defaultLanguage: DEFAULT_LANGUAGE,
    fallbackLng:
      process.env.NODE_ENV === 'production' ? DEFAULT_LANGUAGE : null,
    load: 'languageOnly',
    localesPath: `./${LOCALE_PATH}/`,
    localeSubpaths: LOCALE_SUBPATHS,
    ns: [DEFAULT_NAMESPACE],
    defaultNS: DEFAULT_NAMESPACE,
    interpolation: {
      escapeValue: false,
      formatSeparator: ',',
      format: (value, format) =>
        format === 'uppercase' ? value.toUpperCase() : value,
    },
    detection: {
      order: ['cookie', 'header', 'querystring'],
      caches: ['cookie'],
    },
    backend: {
      loadPath: `/${LOCALE_PATH}/${LOCALE_STRUCTURE}.json`,
      addPath: `/${LOCALE_PATH}/${LOCALE_STRUCTURE}.missing.json`,
    },
  },
};

/* SSR Settings - only change if you understand what you're changing */
if (!process.browser) {
  const fs = require('fs');
  const path = require('path');

  const getAllNamespaces = (p) =>
    fs.readdirSync(p).map((file) => file.replace('.json', ''));
  config.translation = {
    ...config.translation,
    preload: config.translation.allLanguages,
    ns: getAllNamespaces(
      `${config.translation.localesPath}${config.translation.defaultLanguage}`,
    ),
    backend: {
      loadPath: path.join(__dirname, `${LOCALE_PATH}/${LOCALE_STRUCTURE}.json`),
      addPath: path.join(
        __dirname,
        `${LOCALE_PATH}/${LOCALE_STRUCTURE}.missing.json`,
      ),
    },
  };
}

module.exports = config;
```

OUTPUT: 
```json
i18next: initialized { debug: true,
  initImmediate: true,
  ns: [ 'common', 'homepage', 'nav' ],
  defaultNS: 'common',
  fallbackLng: null,
  fallbackNS: false,
  whitelist: false,
  nonExplicitWhitelist: false,
  load: 'languageOnly',
  preload: [ 'en', 'da' ],
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  saveMissing: false,
  updateMissing: false,
  saveMissingTo: 'fallback',
  saveMissingPlurals: true,
  missingKeyHandler: false,
  missingInterpolationHandler: false,
  postProcess: false,
  returnNull: true,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: [Function: returnedObjectHandler],
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  appendNamespaceToCIMode: false,
  overloadTranslationOptionHandler: [Function: handle],
  interpolation:
   { escapeValue: false,
     formatSeparator: ',',
     format: [Function: format] },
  allLanguages: [ 'en', 'da' ],
  defaultLanguage: 'da',
  localesPath: './static/locales/',
  localeSubpaths: true,
  detection:
   { order: [ 'cookie', 'header', 'querystring' ],
     caches: [ 'cookie' ],
     lookupQuerystring: 'lng',
     lookupCookie: 'i18next',
     lookupSession: 'lng',
     lookupFromPathIndex: 0 },
  backend:
   { loadPath:
      '/home/mathias/Kandelborg.dk/static/locales/{{lng}}/{{ns}}.json',
     addPath:
      '/home/mathias/Kandelborg.dk/static/locales/{{lng}}/{{ns}}.missing.json' } }
```

**Comment by jamuhl** [comment] 2018-11-28 13:48
@MathiasKandelborg looks like you only get ns: [DEFAULT_NAMESPACE] but you use common, home and nav -> to you use: https://github.com/i18next/react-i18next/blob/master/example/nextjs/lib/withNamespaces.js everywhere to make sure all those namespaces are known when https://github.com/i18next/react-i18next/blob/master/example/nextjs/pages/_app.js#L75 get called (to pass down all namespaces in initialI18nStore)?

**Comment by MathiasKandelborg** [comment] 2018-11-28 14:12
A  `console.log(initialI18nStore);` In the _app.js `nsFromReactTree.forEach` loop on [line 77](https://github.com/i18next/react-i18next/blob/b4df504a173007e6dd2d4004d9aa3fb071404098/example/nextjs/pages/_app.js#L77)

Gives me this output:

```
{ da:
   { common:
      { title: 'Mathias Kandelborg - Dansk',
        'change-locale': 'Skift sprog' } } }
{ da:
   { common:
      { title: 'Mathias Kandelborg - Dansk',
        'change-locale': 'Skift sprog' },
     homepage: {} } }
```

It also seems like * initializes on every load*

Giving this output on new dev server startupm after namespaces log but before the involuntary debug log:
```
i18next: languageChanged en
i18next::backendConnector: loaded namespace nav for language en {}
i18next::backendConnector: loaded namespace common for language da { title: 'Mathias Kandelborg - Dansk',
  'change-locale': 'Skift sprog' }
i18next: languageChanged en
```

Logging `namespaces` in withNamespace (which is used everywhere) gives the expexted `[ 'common' ]` for LanguageSwicher and the index page gets `[ 'common', 'homepage' ]` as expected.

**Comment by jamuhl** [comment] 2018-11-28 14:17
@MathiasKandelborg do you get the same issue with the sample here: https://github.com/i18next/react-i18next/tree/master/example/nextjs ?!?

**Comment by MathiasKandelborg** [comment] 2018-11-28 14:30
This is the same debug message but from a fresh repo from the link you provided:
```
i18next::backendConnector: loaded namespace common for language de { 'integrates_react-i18next':
   'Dieses Beispiel integriert react-i18next für einfache Übersetzung.',
  pureComponent: 'Entweder t Funktion an Komponente via props weiterreichen.',
  extendedComponent:
   'Oder die Komponente erneut mit dem translate hoc erweiteren.',
  transComponent:
   'Sonst können Sie auch die Komponente <1>Trans</1> verwenden.' }
i18next::backendConnector: loaded namespace page2 for language en { welcomePage2: 'this is page 2',
  link: { gotoPage1: 'Back to page 1' } }
i18next::backendConnector: loaded namespace home for language de { welcome: 'Willkommen zu next.js',
  sample_test: 'test words for de',
  sample_button: 'fire in the wind for de',
  link:
   { gotoPage2: 'Zur Seite 2', gotoPage3: 'Zur Seite 3 (no hoc)' } }
i18next::backendConnector: loaded namespace page2 for language de { welcomePage2: 'Dies ist die 2te Seite',
  link: { gotoPage1: 'Zur Seite 1' } }
i18next: languageChanged en
i18next: languageChanged en
```

I see the compilation message on the server -> then the above message -> then the debug message and then:

```
i18next: languageChanged en
i18next::backendConnector: loaded namespace page2 for language en { welcomePage2: 'this is page 2',
  link: { gotoPage1: 'Back to page 1' } }
i18next::backendConnector: loaded namespace common for language de { 'integrates_react-i18next':
   'Dieses Beispiel integriert react-i18next für einfache Übersetzung.',
  pureComponent: 'Entweder t Funktion an Komponente via props weiterreichen.',
  extendedComponent:
   'Oder die Komponente erneut mit dem translate hoc erweiteren.',
  transComponent:
   'Sonst können Sie auch die Komponente <1>Trans</1> verwenden.' }
i18next::backendConnector: loaded namespace home for language de { welcome: 'Willkommen zu next.js',
  sample_test: 'test words for de',
  sample_button: 'fire in the wind for de',
  link:
   { gotoPage2: 'Zur Seite 2', gotoPage3: 'Zur Seite 3 (no hoc)' } }
i18next::backendConnector: loaded namespace page2 for language de { welcomePage2: 'Dies ist die 2te Seite',
  link: { gotoPage1: 'Zur Seite 1' } }
i18next: languageChanged en
i18next: languageChanged en
```

Followed by a steady income of new debugging messages. 

This behavior also exists in my repo with a few modifications and a bunch of additions(like material-ui which i _know_ doesn't interfere).

In the browser console and what seems like scrolling through 3-4 i18n debug logs I also see the same message several times indicating that it loads several times. But this only logs in my app, not the fresh repo. 

The fresh repo loads both locales on lng change

**Comment by jamuhl** [comment] 2018-11-28 14:34
The question was not regarding the log output...more if the sample does a page flashing / flickering due unloaded translations and therefor does block rendering on the HOC

**Comment by MathiasKandelborg** [comment] 2018-11-28 14:35
It does. Because everything is loading several times. I tried to be verbose in order for you to have the need info.

**Comment by MathiasKandelborg** [comment] 2018-11-28 14:36
It's actually quite easy to see. Just go refresh the page and watch the DOM tree flash on every reload

**Comment by jamuhl** [comment] 2018-11-28 14:47
did you really run the unmodified sample provided here - i really do not get any flickering - rerender.

![nextjs](https://user-images.githubusercontent.com/977772/49159448-d7d17200-f324-11e8-8cbc-d56ed344f4a6.gif)

**Comment by MathiasKandelborg** [comment] 2018-11-28 15:51
Okay, so everything goes back to normal when I don't use thesubPaths logic. That seems to be the root cause for me.

**Comment by jamuhl** [comment] 2018-11-28 16:29
so to say the truth i do not yet completely understand the issue here

**Comment by isaachinman** [comment] 2018-11-28 16:35
It's the same - I just tested. Check out my two latest commits (sorry - accidentally committed to master, didn't see the remote, thought it was my fork).

Your work in `8.3.7` simply _exposed_ a bug that was already lying dormant.

**Comment by isaachinman** [comment] 2018-11-28 16:40
@retep0214 and @MathiasKandelborg does 896c979df516cde7a4ad55d05cfdcf9840dd364c fix your problem?

If you don't want to worry about the details under the hood, feel free to install [next-i18next](https://github.com/isaachinman/next-i18next) via npm.

**Comment by MathiasKandelborg** [comment] 2018-11-28 16:47
It did! Thanks and I'll check out the package soon maybe, but I like having the code. Awesome work though!

**Comment by retep0214** [comment] 2018-11-28 16:47
Hello, I found the next-i18next yesterday and installed it to my project, the problem is fixed now :) , the installation and configuration is easier !

However, my teammate found that the data structure of the redux store will be changed after installing the next-i18next. Also, the server side can get the store and client-side get nothing. Is this the bug of next-i18next or we configured wrong?

(I will create the issue on next-i18next github later)

**Comment by isaachinman** [comment] 2018-11-28 16:56
@retep0214 Please do open an issue over at [next-i18next](https://github.com/isaachinman/next-i18next) and I'll take a look at it there. In general the project is still young and there may be a genuine issue with Redux. It sounds like you're having a problem with context and/or nested providers, though.

**Closed by isaachinman** 2018-11-28 16:56 UTC
Labels: next.js
