### ISSUE TITLE
Iterating over a big array is extremely slow (RN-expo)

### ISSUE THREAD

**Issue by antonioaltamura** [i18next/react-i18next#432] opened 2018-05-12 15:15 UTC
I'm new to i18next (and RN too). I'm trying to iterate over a pretty big array (500 items). I've sadly noticed navigating on Search.js component takes several seconds (even in release build!).
The same component takes few instants to load in case of plain javascript array, if I iterate over an array inside a i18next resource it gets slower a lot.

this is the env:
```
create-react-app
i18next + react-i18next
```

I followed your example for react-native-expo. 
**i18n.js**

```
import i18n from 'i18next';
import {reactI18nextModule} from 'react-i18next';
i18n
	.use(reactI18nextModule)
	.init({
		fallbackLng: 'en',
		resources: {
			de: {
				home: {
					title: 'Willkommen'
				},
				data: { data:require("./locales/de.json") }
			},
			en: {
				home: {
					title: 'welcome'
				},
				data: { data:require("./locales/en.json") }
			}		
		},
		ns: ['common'],
		defaultNS: 'common',
		debug: false,
		interpolation: {
			escapeValue: false,
		}
	});

export default i18n;
```

**DB.js** (I'm sure there is a better way to implement this object and inject the `t()` function)
```
let DB = (props) => (
	{
		getAll: () => props.t('data:data', { returnObjects: true }),
		get: i => props.t(`data:data.${i}`, { returnObjects: true }),
	}
);
export default DB;
```

The Component (**Search.js**)
```
import React, { Component } from "react";
import { Text, View, FlatList, TouchableOpacity } from 'react-native';
import $DB from './DB';
import { translate } from 'react-i18next';

class Item extends Component {
	render() {
		return (
			<TouchableOpacity {...this.props}>
				<Text style={{fontSize: 14,color:"grey",borderColor: '#e2e2e2',borderWidth: 1,padding:15}}>{this.props.children}</Text>
			</TouchableOpacity>

		);
	}
}
@translate(['data'], { wait: true })
export default class Search extends Component {
	state = {
		search:""
	}
	DB = null;
	componentDidMount(){
		this.DB = $DB(this.props)
		this.setState({
			DB: this.DB.getAll()
		})
	}
	render() {
		const { params } = this.props.navigation.state;
		return (
			<View>
				<FlatList
					data={this.state.DB}
					keyExtractor={(item, index) => index}
					renderItem={({item}) => <Item onPress={() => this.props.navigation.navigate('Detail',{id:item.id})}>{item.Title}</Item>}
				/>
			</View>
		);
	}
}

```

**en.json**
```
[
{"id":0,"Title":"Title 01"},
{"id":1,"Title":"Title 02"},
//...500 items...
]
```

**Comment by jamuhl** [comment] 2018-05-12 21:18
the problem is returning an object in i18next means it will iterate over every member in the object and apply the interpolation, nesting,...not very efficient.

if you do not need interpolation, nesting and other translation functionality in your accessed db values it might be more efficient to access those values from some custom object using current i18next.language

**Comment by antonioaltamura** [comment] 2018-05-12 21:35
I not sure I get your advice: are you saying it would be more efficient to use a mega-object with 500 items per language and use the current language for accessing it?
I don't think it's the best way to handle this. I have 6-7+ different languages, It would ends up with a 500kB javascript array.
That (sync) `require("./locales/en.json")` you see in `i18n.js` is temporary, I want to lazy-load the resources (as soon as I get how to do it).

I confirm I do not need interpolation or other i18next functionalities, I just the the array in the current language.

**Comment by jamuhl** [comment] 2018-05-13 08:51
the problem is here: https://github.com/i18next/i18next/blob/master/src/Translator.js#L103 like said for every value in your "db" i18next translates that....means if you got 500 items it will call 500 times the translate function.

you might try using this: https://github.com/benwixen/react-native-filesystem for the backend

**Comment by antonioaltamura** [comment] 2018-05-13 09:45
I see there are a lot of function calls I don't need.
There is no way to disable this by default?

You are suggesting react-native-filesystem in order to try resolve this issue or just for lazyload?

**Comment by jamuhl** [comment] 2018-05-13 11:25
For the lazy loading.

No there is no option to disable this. i18n frameworks are meant for translations. Not for simulating a translated database ;)...so that's why i suggested to move that "db" into some own store and access the right data using i18next.language. That's what we do for our product catalogs in the past.

**Comment by antonioaltamura** [comment] 2018-05-13 11:31
Thanks, very clear :)

Any chance you have an example for react-native-filesystem as i18next backend? Can't find any.

**Comment by jamuhl** [comment] 2018-05-13 11:32
No...not really...but i could write your stuff for $100/hour ;)...honestly should be rather easy...takes some time...but nothing one should not be able todo.

**Comment by antonioaltamura** [comment] 2018-05-13 11:33
I will try to figure it out (keeping in mind your offer) :)

**Comment by jamuhl** [comment] 2018-05-15 11:28
closing this for now...

**Closed by jamuhl** 2018-05-15 11:28 UTC
