### ISSUE TITLE
How do you collect all the namespaces when rendering on the server?

### ISSUE THREAD

**Issue by norbert-yoimo** [i18next/react-i18next#259] opened 2017-06-08 13:35 UTC
I'm trying to figure out how could I collect all the namespaces that I need to load for a particular route, but I'm drawing blanks here. There is a topic in the docs that uses `loadNamespaces`, which expects the list of components to render as an argument, however, I can't find a way to determine those components.

With react router V4, I can easily determine my top level component, based on the path, and look at its namespaces, however, the top level component contains several children, some of which might need more namespaces.

How do I drill down into these children to find their namespaces? Or alternatively, is there a way to hook into the `translate` function, so that could return me the list of namespaces?

**Comment by jamuhl** [comment] 2017-06-08 13:37
you don't need to know. Every translate hoc gets set which namespaces are needed for rendering wrapped components -> it will load the needed files on demand.

**Comment by jamuhl** [comment] 2017-06-08 13:40
Calling translate - you would already be late. But you can wrap every component with the translate hoc.

My tip is to not going overcrazy with namespaces...not every component needs it's own namespace - i suggest making them for group of views (eg. admin area, ...). Still you can organise inside the namespace using `.` separated keys.

**Comment by jamuhl** [comment] 2017-06-08 13:43
i guess this is for universal rendering?

**Comment by norbert-yoimo** [comment] 2017-06-08 13:44
To confirm I understand you right, when you say "you don't need to know", you are referring to just letting the browser load missing namespaces it on the client side, through something like the XHR backend, is that correct?

Or am I missing something?

Yes this is for universal rendering.

**Comment by jamuhl** [comment] 2017-06-08 13:48
Yes, was for client side rendering...on the server it's different.

Good balance might be reducing the number of namespaces - so you got control over which namespace is needed on which route. So you have something like `routeNamespace`, `commonNamespace`, `sharedNamespace` to load -> so you could add them to the outer components list of namespaces.

Really the problem is you need to know the namespaces upfront - before render on the server - so those are asserted to be loaded.

**Comment by norbert-yoimo** [comment] 2017-06-08 13:51
> Really the problem is you need to know the namespaces upfront - before render on the server - so those are asserted to be loaded.

Exactly, this is the heart of the problem. I'm thinking about saving the list of namespaces somewhere next to the routes, so after a routing decision has been made, I can get the list of namespaces from the route itself.

I want to split up the localization files per subpages, to give the translators an easier time for figuring out where the texts will end up on the page, not sure if it's a good idea yet.

**Comment by jamuhl** [comment] 2017-06-08 13:56
hm...best option would be using the incontext editor of http://locize.com for translators: http://locize.com/incontext-editor.html would make every translation be a click away. But outside of what i18next provides for free - locize is our localization as a service tier. But you might have a look anyway...has a lot of other goodies beside the incontext editor.

Splitting up into subpages might work - until code changes and stuff got moved around...hard to say. Might even depend on how often your project will add new features or adapt to customer wishes.

**Comment by jamuhl** [comment] 2017-06-16 12:58
closing for now...feel free to reopen if needed.

**Closed by jamuhl** 2017-06-16 12:58 UTC
