### ISSUE TITLE
t function from useTranslation is unstable in concurrent mode

### ISSUE THREAD

**Issue by woodreamz** [i18next/react-i18next#1691] opened 2023-10-31 20:20 UTC
## 🐛 Bug Report

The bug is really well explained in #1599. This issue has been also reported in #1636. Those issues have been closed without being fixed.

When enabling concurrent mode in React, the `t` function changes and creates extra renders. i18n.t is not doing that. For now, it's not major as concurrent mode is not enabled in production build but could become major in a futur react release.

The issue seems to be in `useTranslation`. I am trying to find a fix and propose a PR. This issue will help to track the work.

For now, concurrent mode is enabled with [StrictMode](https://react.dev/reference/react/StrictMode). 

> You can use [<StrictMode>](https://react.dev/reference/react/StrictMode) to help surface concurrency-related bugs during development. Strict Mode doesn’t affect production behavior, but during development it will log extra warnings and double-invoke functions that are expected to be idempotent.
Source: [react.dev](https://react.dev/blog/2022/03/29/react-v18#gradually-adopting-concurrent-features)

## To Reproduce

In this [codesandbox](https://codesandbox.io/s/react-i18next-concurrent-mode-wjrtjt), you can se in the console that the useEffect on i18n is called **2** times and the useEffect on t is called **3** times.

```js
import "./i18next";
import { useTranslation } from "react-i18next";
import { useEffect } from "react";

export default function App() {
  const { i18n, t } = useTranslation();

  useEffect(() => {
    console.log("useEffect with i18n");
  }, [i18n]);

  useEffect(() => {
    console.log("useEffect with t");
  }, [t]);

  return i18n.t("text");
}
```

## Expected behavior

useEffect with t as dependency should be called **2** times.

**Comment by woodreamz** [comment] 2023-10-31 20:37
It seems to be caused by: https://github.com/i18next/react-i18next/blob/461986289fe82a70a5ddae9078c7c7e68f86f7dd/src/useTranslation.js#L117

**Comment by qq831799** [comment] 2024-01-16 01:53
Same issue here, and my react-i18next version is 12.3.1

**Comment by timheilman** [comment] 2024-01-31 20:30
same issue here. Thank you @woodreamz for your sleuthing so far.

**Comment by adrai** [comment] 2024-02-01 08:41
> It seems to be caused by:
> 
> https://github.com/i18next/react-i18next/blob/461986289fe82a70a5ddae9078c7c7e68f86f7dd/src/useTranslation.js#L117

was introduced [here](https://github.com/i18next/react-i18next/commit/ecae71f68fb7851e3a2813be0d405050af6ecaf3#diff-86728002da54c328b2606ba95801af1262223ecf3d531cbd6d4a5eab9df7d014R82) by @medihack because of [this](https://github.com/i18next/react-i18next/issues/1272#issuecomment-791745096)

**Comment by timheilman** [comment] 2024-02-01 17:37
I have a draft PR to fix this at https://github.com/i18next/react-i18next/pull/1716 ; still working through the contribution checklist.
I'm not sure hook-based testing including strictMode is yet available; I've found this, which was _just_ merged:

https://github.com/testing-library/react-testing-library/pull/1241

but I haven't looked into hook-testing support using it, yet

**Comment by adrai** [comment] 2024-02-04 07:15
Should be fixed with v14.0.2

**Comment by timheilman** [comment] 2024-02-04 18:43
Thank you @woodreamz for generating a minimal reproduction of the bug and @adrai  for maintaining this repo and providing me the opportunity to contribute :)

**Comment by adrai** [comment] 2024-02-05 08:39
reverted with v14.0.3 and waiting for a better fix...  because of [this](https://github.com/i18next/react-i18next/pull/1716#issuecomment-1926458005)

**Comment by timheilman** [comment] 2024-02-06 18:33
Sorry for the false start! I hope #1720 will be better forward progress.

**Closed** 2024-02-06 18:46 UTC

**Comment by wr-lhiggitt** [comment] 2024-02-26 17:50
This is still occurring for me in 14.0.5

**Comment by timheilman** [comment] 2024-02-26 18:15
I'm afraid I can reliably reproduce using the minimal reproduction from the original post in 14.0.3, and I cannot reproduce using 14.0.5 . I'm still interested in the bug; are you able to see the bug using the reproduction in the original post?  If not, can you provide a different minimal reproduction with expected result vs actual result?

**Comment by MarlonVCendron** [comment] 2024-02-26 18:44
I don't know if that's related or not. But having `t` as a dependency on `useMemo` makes it render indefinetely, but as a dependency on `useEffect` it works normally. This only happens in a specific component, I wasn't able to create a minimal reproduction of the bug, so maybe it's just something I'm doing wrong, but can't figure it out.

```ts
const tools = useMemo(() => {
    console.log('useMemo')
    return []
  }, [t])

  useEffect(() => {
    console.log('useEffect')
  }, [t])
 
```
