### ISSUE TITLE
Using it with express server loads the langing page twice

### ISSUE THREAD

**Issue by ambardas1989** [i18next/react-i18next#288] opened 2017-08-18 20:45 UTC
When I use react-i18next with express server, I see that the landing page is getting loaded twice if we use the below statement:
......some code
**app.use(express.static(__dirname + '/static'))**
....remaining code

Without using this part of the code, the page loads only once.
I have an API call inside componentDidMount to a backend service on page load; thus the double loading of the page is making two API calls which is resulting in serious errors.

A quick solution to why this error occurs and the solution for the same?

A quick response will be highly appreciated as this is causing a major delivery blockage.

**Comment by jamuhl** [comment] 2017-08-19 17:09
no idea what it has to do with the static folder - do you load translations from there?

if so the second load is triggered as translations where loaded -> set wait option to avoid that

**Comment by jamuhl** [comment] 2017-08-22 08:23
any update?

**Comment by ambardas1989** [comment] 2017-08-22 20:14
Hi Jamhul,

Yes, with consultation of few senior experts here we figured out the issue.
The problem was because of webpack's nature which we were using for bundling.

1. Once we injected the bundle from html as <script type = "text/javascript" src=".\build\bundle.js"> </script>
2. The app.use(express.static(__dirname + '/static')) which we mentioned above injected it again.

Removing #1 from the html file resolved the issue.

Thanks for your response!

**Comment by jamuhl** [comment] 2017-08-23 05:33
great you figured that out...but strange it gets double injected...well anyway - you found the cause and thats awesome. will close this issue for now.

And don't forget to star react-i18next and/or have a look at https://locize.com our i18next as a service tier ;)

**Closed by jamuhl** 2017-08-23 05:33 UTC
