### ISSUE TITLE
NextJS example won't Server Side Render after combining "with-apollo" example

### ISSUE THREAD

**Issue by mikepuglisi** [i18next/react-i18next#593] opened 2018-10-29 17:46 UTC
I've tried to resolve this issue on my own unsuccessfully for literally days now. I set up an isolated repository to demonstrate the issue.

https://github.com/mikepuglisi/next-js-with-apollo-and-i18next

Summary:

When NamespacesConsumer and ApolloProvider are both utilized in _app.js, server side rendering of the Apollo <Query> component no longer occurs. You will see the "Loading..." text before the graphql data is presented which indicates that the data is being loaded and rendered client side. I also included a screenshot in the repository to illustrate the issue.

Any assistance would be greatly appreciated. Thank you.

**Comment by jamuhl** [comment] 2018-10-29 18:15
did you try nesting the consumer inside the apolloprovider?

**Comment by jamuhl** [comment] 2018-10-29 18:40
Well idk...does apollo need to set some initialState? if so you might need to merge that. Honestly would be great if you try to figure out what happens...won't be of much help here

**Comment by mikepuglisi** [comment] 2018-10-29 18:50
withApollo does something with getInitialState here

https://github.com/mikepuglisi/next-js-with-apollo-and-i18next/blob/3_nesting_reversal/lib/with-apollo-client.js

I'm new to a lot of this stuff, so I'm grasping at straws really.

I see someone else had an issue merging the two, but they apparently resolved it

https://github.com/zeit/next.js/issues/3779

 I think they were merging the older "with-i18next" example that's in the next.js examples though. Maybe I'll try that. 

Hopefully someone else already uses NextJS, i18next and apollo and will be able to provide some insight.

**Comment by jamuhl** [comment] 2018-10-29 18:57
next.js passes down information via initialState from server to client.

Both set that - i18next here: https://github.com/i18next/react-i18next/blob/master/example/nextjs/lib/withI18next.js#L30

**Comment by jamuhl** [comment] 2018-10-29 18:58
So you need to merge both to get it work.

**Comment by mikepuglisi** [comment] 2018-10-29 20:26
I'm trying to apply your advise, but again my lack of experience with these frameworks leaves me spending large amounts of time getting nowhere fast. If you could provide a little more insight on what you mean, I'm sure the end result will be useful for many others going forward.

Note that the function you mentioned above never actually gets hit when ApolloProvider is present.

It isn't clear to me how to "merge both [initalStates] to get it work." 
```
  Extended.getInitialProps = async ctx => {
    console.log('nextjs:getInitialProps');
    const composedInitialProps = ComposedComponent.getInitialProps
      ? await ComposedComponent.getInitialProps(ctx)
      : {};

    const i18nInitialProps = i18nInstance.getInitialProps(ctx.req, reportedNamespaces);

    return {
      ...composedInitialProps,
      ...i18nInitialProps,
    };
  };
```

**Comment by jamuhl** [comment] 2018-10-29 21:06
I gave you the direction to solve it - merging the initialProps stuff - how to do it...idk...sorry but would take me to much time to digg into that myself (time i don't have). Hopefully someone else can catch up...or try asking for help at stackoverflow.

**Comment by isaachinman** [comment] 2018-10-30 01:18
@mikepuglisi If you expect Apollo to do some data fetching before SSR, you need to set that up inside `getInitialProps`. NextJs and Apollo should work just fine together and this is a question that absolutely belongs on StackOverflow, not a GitHub issue.

**Comment by isaachinman** [comment] 2018-10-30 02:41
I'm not entirely sure what you're saying or trying to accomplish, but in general you can use `getInitialProps` in any component with NextJs to delay SSR until you have the data you need. Assuming Apollo's methods return promises, that's pretty much job done.

You shouldn't need to touch `withI18next` at all. If you're trying to manage translation data with Apollo, that's not something we'd recommend or even be able to give advice on.

Good luck, you can always feel free to email me directly if you'd like advice.

**Comment by jamuhl** [comment] 2018-10-30 07:59
closing this for now - not that we do not want to help - but really not belongs into an issue. Thanks for understanding that we can't solve each coding problem in codebases. Not sure - someone should make a profession out of it -> consulting that does not suck but solves problem 🤔

**Closed** 2018-10-30 07:59 UTC
Labels: next.js, question

**Comment by ericyip** [comment] 2018-11-06 18:46
@mikepuglisi After I update react-apollov2.30 `react-apollo@next`, SSR is working
https://github.com/apollographql/react-apollo/pull/2533

**Comment by jandolezal71** [comment] 2019-05-03 10:23
I know the issue is closed now, but i struggled with this too. If you did not make it, there is my solution :-)

```javascript
import { appWithTranslation } from '~/lib/i18n';
import attachGraphqlClient from '~/lib/graphqlClient';

class MyApp extends App {
	render() {
		const { Component, pageProps } = this.props;

		return (
			<Container>
				<Component {...pageProps} />
			</Container>
		);
	}
}

const GraphqlComponent = attachGraphqlClient(() => <div />);
const TranslatedComponent = attachGraphqlClient(() => <div />);

const ComposedMyApp = compose(
	attachGraphqlClient,
	appWithTranslation,
)(MyApp);

ComposedMyApp.getInitialProps = async (ctx) => {
	return {
		...(await GraphqlComponent.getInitialProps(ctx)),
		...(await TranslatedComponent.getInitialProps(ctx)),
	};
};

export default ComposedMyApp;
```

**Comment by KumarAbhirup** [comment] 2019-05-15 05:37
Hey, @jandolezal71, I am struggling with the same issue. Please tell from where did you get `~/lib/i18n`?

**Comment by KumarAbhirup** [comment] 2019-05-15 07:09
Posted a stackoverflow question: [https://stackoverflow.com/questions/56143491/server-side-rendering-with-react-apollo](https://stackoverflow.com/questions/56143491/server-side-rendering-with-react-apollo)
