### ISSUE TITLE
/example/test-jest does not work with latest react

### ISSUE THREAD

**Issue by hmzlam** [i18next/react-i18next#1134] opened 2020-06-13 15:50 UTC
updating  /example/test-jest  to latest react gives some warning in tests

"dependencies": {
    "enzyme": "3.8.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "i18next": "^19.4.5",
    "i18next-browser-languagedetector": "^4.2.0",
    "i18next-http-backend": "^1.0.15",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-i18next": "^11.5.1",
    "react-scripts": "3.4.1"
  },

'npm test'
console.warn node_modules/react-i18next/dist/commonjs/utils.js:22
      react-i18next:: You will need pass in an i18next instance by using initReactI18next

beside this the 'npm start' does not work without adding suspense

**Comment by adrai** [comment] 2020-06-13 18:09
Yes, was not updated for a long time...
I just committed a fix.

**Comment by adrai** [comment] 2020-06-13 18:21
Is this working for you?

**Comment by hmzlam** [comment] 2020-06-13 23:06
only 1/5 test cases passes
App.test.js works, but all other tests does not work there is this warning

Translation.test.js
Trans.test.js
UseTranslation.test.js
WithTranslation.test.js

  Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.

**Comment by adrai** [comment] 2020-06-14 05:37
I have no such warning... have you npm installed again?

**Comment by hmzlam** [comment] 2020-06-14 19:56
why do you expect them to work correctly? you only made changes to App.test.js
all other tests does not have suspense wrapper.

**Comment by adrai** [comment] 2020-06-14 19:58
This change fixed the rest for me: https://github.com/i18next/react-i18next/commit/cab7d32ae6507c07ecda7e17938c2cbdfedbe374#diff-98ed63c85f49fb099a5257cf9520a36c

**Comment by adrai** [comment] 2020-06-14 20:07
You're right... might be timing... did just checked to output in my console... did not check the content of the other files

**Comment by adrai** [comment] 2020-06-14 20:16
Updated, like defined here: https://react.i18next.com/misc/testing#testing-without-stubbing

**Comment by adrai** [comment] 2020-06-14 20:16
https://github.com/i18next/react-i18next/commit/faceba22696d7cc89091f36010faed021e5d1932

**Comment by hmzlam** [comment] 2020-06-15 01:59
works perfectly, thank you

**Closed** 2020-06-15 04:39 UTC

**Comment by adrai** [comment] 2020-06-15 06:13
fyi: as the test-jest example was intended for stubbing, I changed the example: https://github.com/i18next/react-i18next/commit/d8c7bba381dcb8cdac9339ff62762fed5d2b581e

**Comment by hmzlam** [comment] 2020-06-15 09:38
i don't want to push it too far, but is it possible to test with the same production state, just select the language to test with and run the tests, for example using preload which does not preload really, only ressources; ....  do the preload brefore running the tests.

**Comment by adrai** [comment] 2020-06-15 09:40
Sorry I don’t know what you are asking for... 🤷‍♂️

**Comment by jamuhl** [comment] 2020-06-15 09:41
You can add all resources using i18next API -> then run tests

But actually - do you test the translations? Is this a good idea?

You can do it...but I don't recommend testing translated content...that has nothing todo with unit testing

**Comment by hmzlam** [comment] 2020-06-15 09:48
dor now test-jest do thet tests by disabling i18next , for example if we have

<h1>{t('app.hello')}</h1>

with en : {'app.hello";'Welcome to React"}


in tests we will expect h1.innerHtml to be app.hello .

why we can't preload english translation and expect  h1.innerHtml to be Welcome to React

you have preload option in i18next but if you test it you will find you end up with suspense warning

so for tests the only options that makes everything works without errors is ressource:....

**Comment by jamuhl** [comment] 2020-06-15 09:51
you can preload...set useSuspense to false for test...it does just not add values

as you're testing frameworks not your code...but do what you like todo...it's your code

**Comment by hmzlam** [comment] 2020-06-15 10:01
thank you,  i understand your point, 
but just to mention , using real life data gives you more than testing frameworks, 
 - testing if your locale files are ok (served from the hosting)
 - testing if your components width(text length) does not affect your design 
 - testing if complexe languages letters are rendred correctly

**Comment by jamuhl** [comment] 2020-06-15 10:04
Won't argue...do what you like todo...it's all there - test translations if you like todo so

**Comment by hmzlam** [comment] 2020-06-15 10:05
and i tried preload with setsuspense, it gives the same results as now , no preloading happened

**Comment by hmzlam** [comment] 2020-06-15 10:10
maybe this is another issue to open

**Comment by jamuhl** [comment] 2020-06-15 10:11
https://www.i18next.com/how-to/add-or-load-translations 

a) ADD not load!
b) make sure all this is done before running tests (timing, async)

**Comment by hmzlam** [comment] 2020-06-15 10:17
:) We are back to point 0, no testing without using the magical 'ressources'
thank you anyway, I really appreciate your help. I was on the point to think if i use i18n i should drop testing at all

**Comment by jamuhl** [comment] 2020-06-15 10:28
It's like testing loading async data...no magic...

test case a) not loaded yet -> suspense fallback UI is shown
test case b) loaded -> UI is shown

there is no difference in loading translations or loading backend data!!!
