### ISSUE TITLE
Types broke in 23.12.1

### ISSUE THREAD

**Issue by hieuminh1810** [i18next/react-i18next#1760] opened 2024-07-15 08:45 UTC
## 💥 Regression Report

I have seen keys that are not in the JSON file

![Screenshot 2024-07-15 at 3 31 36 PM](https://github.com/user-attachments/assets/347b5176-d6a5-48ec-93e7-7b2786845ca0)

## Last working version

Worked up to version: "i18next": "22.4.6",   "react-i18next": "12.1.1"

Stopped working in version:  "i18next": "^23.12.1",   "react-i18next": "^14.1.2"

## To Reproduce

update  to the latest version ("i18next": "^23.12.1",   "react-i18next": "^14.1.2")

```
export const RESOURCES_LANGUAGES = {
  en: {
    translation: en,
  },
} as const;
```

```
import 'i18next';
import { RESOURCES_LANGUAGES } from '@locale/index';

declare module 'i18next' {
  interface CustomTypeOptions {
    resources: typeof RESOURCES_LANGUAGES.en;
  }
}

```

## Expected behavior

The keys shown are all in my JSON file

## Your Environment

- *runtime version*: "react": "18.2.0", "node": ">=18", "typescript": "^5.5.3"
- *i18next version*:  "^23.12.1"  , "react-i18next": "^14.1.2",
- *os*: Mac

**Comment by adrai** [comment] 2024-07-15 10:25
This seems to work: https://github.com/i18next/react-i18next/tree/master/example/react-typescript/simple

Please provide a minimal reproducible example repository...

**Comment by adrai** [comment] 2024-07-15 11:08
duplicate of: https://github.com/i18next/i18next/issues/2214

**Closed by adrai** 2024-07-15 11:08 UTC
Labels: typescript
