### ISSUE TITLE
Unable to load the translations from json files

### ISSUE THREAD

**Issue by ronald-chun** [i18next/react-i18next#507] opened 2018-09-04 10:09 UTC
I am using Expo to build a react native application
The translate is work if I put the translations in the i18n.init() config (i.e. resources: { en: {...}, de: {...}}, like the example, here https://github.com/i18next/react-i18next/blob/d899be42f240a46de0f88f2c8fd1beedf05df60c/example/react-native-expo/js/i18n.js#L21-L59)

However, I want to use json file to store the translations thus I can pass the translate process to other colleagues easily.

I followed the config to init, but it cannot translate and  I got the error message  "failed parsing ./locales/en/common.json to json"

i18n.js
`import i18n from 'i18next'
import { reactI18nextModule } from 'react-i18next'
import Expo from 'expo'

import Backend from 'i18next-xhr-backend'

const languageDetector = {
	type: 'languageDetector',
	async: true, // flags below detection to be async
	detect: (callback) => { return /*'en';*/ Expo.DangerZone.Localization.getCurrentLocaleAsync().then(lng => { callback(lng.replace('_', '-')) }) },
	init: () => {},
	cacheUserLanguage: () => {}
}

i18n
	.use(Backend)
	.use(languageDetector)
	.use(reactI18nextModule)
	.init({
			fallbackLng: 'en',
			ns: ['common'],
			defaultNS: 'common',
			debug: true,
			load: 'languageOnly',
			backend: {
				loadPath: './locales/{{lng}}/{{ns}}.json',
			},
			react: {
				wait: true,
				bindI18n: 'languageChanged loaded',
			},
		}, (err, t) => {
			console.log('Loading Done')
			console.log('Err:')
			console.log(err)
			console.log('t:')
			console.log(t)
			console.log(i18n.t('title'))
		}
	)

export default i18n`

the render part of the screen
`render () {
		return (
			<View style={styles.mainContainer}>
				<Header>
					<Left>
					</Left>
					<Body>
					<Text>Goals</Text>
					</Body>
					<Right>
						<Button transparent onPress={() => this.onClick()}>
							<Icon name='ios-person'/>
						</Button>
					</Right>
				</Header>
				<ScrollView>
					<Text> {i18n.t('title')}</Text>
				</ScrollView>
			</View>
		)
	}`

locales/en/common.json
`
{
	"title": "en-us Tesing"
}
`

The file structure
[
![screen shot 2018-09-04 at 18 03 53](https://user-images.githubusercontent.com/6634823/45025036-fb11bb80-b06c-11e8-8767-2c4c1056aa02.png)
](url)

The error log and the app screen
<img width="1040" alt="screen shot 2018-09-04 at 18 07 51" src="https://user-images.githubusercontent.com/6634823/45025236-83905c00-b06d-11e8-994f-3b0b78e05f91.png">
![simulator screen shot - iphone x - 2018-09-04 at 18 09 10](https://user-images.githubusercontent.com/6634823/45025292-a753a200-b06d-11e8-8c11-4239fcb4f7e6.png)

**Comment by ronald-chun** [comment] 2018-09-04 10:35
@jamuhl Thanks for your reply

The common.json is just like this, it has only one translation key since I am still testing how to use this translation

common.json
`{
	"title": "en-us Testing"
}
`
![screen shot 2018-09-04 at 18 33 55](https://user-images.githubusercontent.com/6634823/45026566-44fca080-b071-11e8-964f-67d756e0be3e.png)

**Comment by jamuhl** [comment] 2018-09-04 10:44
that translations do not get served by your webpack/metro bundler -> those files need to be reachable via xhr. For cra created react apps there is a public folder which gets hosted during development - not sure if there is something similar for reactnative...

**Comment by ronald-chun** [comment] 2018-09-05 03:38
@jamuhl Thank you for your reply. 
It seems that there is no public folder (or similar concept) in React Native. I will try to find is there any other solution for React Native.
Anyway, thank you.

**Comment by jamuhl** [comment] 2018-09-05 05:51
@ronald-chun meanwhile you figure out to solve this you could try using https://locize.com -> comes 14days for free -> just replace the xhr backend with https://github.com/locize/i18next-locize-backend 

this way you at least have a working solution for now (for loading and save missing)

**Comment by jamuhl** [comment] 2018-09-13 09:19
closing this for now...the cause of the problem should be clear...would be great if you found a solution you share it here for others to pick it up

**Closed by jamuhl** 2018-09-13 09:19 UTC
