### ISSUE TITLE
reactI18nextModule undefined property 'type'

### ISSUE THREAD

**Issue by rntorm** [i18next/react-i18next#317] opened 2017-10-05 07:58 UTC
I have a problem using the new reactI18nextModule. Without it, works normally.

```
import i18n from 'i18next';
import LocizeBackend from 'i18next-locize-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { reactI18nextModule } from 'react-i18next';

i18n
  .use(LocizeBackend)
  .use(LanguageDetector)
  .use(reactI18nextModule)
```

![screen shot 2017-10-05 at 10 47 23](https://user-images.githubusercontent.com/4128109/31216068-dd9ee08c-a9ba-11e7-8cc3-95462bf4036b.png)

**Comment by jamuhl** [comment] 2017-10-05 08:20
what version of react-i18next are you using? seems reactI18nextModule is undefined -> older than v6

**Comment by rntorm** [comment] 2017-10-05 09:53
Thanks, indeed had not updated to 6.0.0. Updated to 6.0.5 now and removed the provider from index.js but another error appears.

```
import './i18n/i18n'
```

18n setup 
```
import i18n from 'i18next';
import LocizeBackend from 'i18next-locize-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { reactI18nextModule } from 'react-i18next';

export default i18n
  .use(LocizeBackend)
  .use(LanguageDetector)
  .use(reactI18nextModule)
  .init({
    fallbackLng: process.env.REACT_APP_LOCIZE_FALLBACK_LANG,
    appendNamespaceToCIMode: true,
    saveMissing: process.env.REACT_APP_LOCIZE_SAVE_MISSING === 'true',

    // have a common namespace used around the full app
    ns: ['translations'],
    defaultNS: 'translations',

    debug: process.env.REACT_APP_LOCIZE_DEBUG === 'true',
    keySeparator: '### not used ###', // we use content as keys

    backend: {
      projectId: process.env.REACT_APP_LOCIZE_PROJECT_ID, // <-- replace with your projectId
      apiKey: process.env.REACT_APP_LOCIZE_KEY,
      referenceLng: 'en'
    },

    interpolation: {
      formatSeparator: ',',
      format: function(value, format, lng) {
        if (format === 'uppercase') return value.toUpperCase();
        return value;
      }
    },

    react: {
      wait: true
    }
  });
```
Error:
![screen shot 2017-10-05 at 12 50 14](https://user-images.githubusercontent.com/4128109/31221276-ca104fcc-a9cb-11e7-8a82-85150be99dd1.png)

**Comment by jamuhl** [comment] 2017-10-05 10:04
looks like i18n does not get set: https://github.com/i18next/react-i18next/blob/master/src/context.js#L28

else it would be defined here: https://github.com/i18next/react-i18next/blob/master/src/I18n.js

do you get any console output from i18next before this error occures? i18next initialized...or backend loaded statements?!?

Looks somehow you not import the i18n file

**Comment by rntorm** [comment] 2017-10-05 10:11
I get the console output AFTER the error

**Comment by jamuhl** [comment] 2017-10-05 10:13
where do you `import './i18n/i18n'` seems to late

**Comment by rntorm** [comment] 2017-10-05 12:49
I import it in index.js but its imported after App component, that might be the problem. I will test it soon.

**Comment by rntorm** [comment] 2017-10-05 13:01
So I switched to order, now getting this:

![screen shot 2017-10-05 at 15 59 58](https://user-images.githubusercontent.com/4128109/31228487-5d7804c0-a9e6-11e7-9bf1-3b90fdc78009.png)

**Comment by jamuhl** [comment] 2017-10-05 13:06
Would need a sample to reproduce...hard to say without having the code and debugger at hand.

**Comment by jamuhl** [comment] 2017-11-13 15:56
closing for now...feel free to reopen with reproducible code sample

**Closed by jamuhl** 2017-11-13 15:56 UTC

**Comment by waqaramjad** [comment] 2019-11-01 07:39
same issue here

**Comment by jamuhl** [comment] 2019-11-01 07:47
@waqaramjad without reproducible sample I can't see how to help with this...could be anything and everything
